@echo off
echo starting php-cgi...
RunHiddenConsole.exe E:\server\php\php-cgi.exe -b 127.0.0.1:9000 -c E:\server\php\php.ini
echo starting nginx...
RunHiddenConsole.exe E:\server\nginx\nginx
echo redis-server...
RunHiddenConsole.exe E:\server\redis\redis-server
exit